version: 2
updates:
  - package-ecosystem: npm
    directory: /pt-agent-daemon
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /pt-agent-daemon
    schedule:
      interval: weekly
